[package]
authors = ["Curtis McEnroe <programble@gmail.com>"]
name = "viola"
version = "0.0.0"

[[bin]]
name = "vio"

[dependencies]

[dev-dependencies]
quickcheck = "0.3.1"
quickcheck_macros = "0.2.28"
